edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Basic formatting
use_small_heuristics = "Default"
use_try_shorthand = true
use_field_init_shorthand = true
merge_derives = true
reorder_imports = true
