version: 3
tasks:
  lint:
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings
  format:
    cmds:
      - cargo fmt --all -- --check
  fix:lint:
    cmds:
      - cargo clippy --all-targets --all-features --fix -- -D warnings
  fix:format:
    cmds:
      - cargo fmt --all
  install:cli:
    cmds:
      - cargo install --path coupe-cli
