version: 3
tasks:
  lint:
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings
  format:
    cmds:
      - cargo fmt --all -- --check
  fix:lint:
    cmds:
      - cargo clippy --all-targets --all-features --fix -- -D warnings
  fix:format:
    cmds:
      - cargo fmt --all
  install:cli:
    cmds:
      - cargo install --path coupe-cli
  release:sentinel:
    cmds:
      - docker build -t coupe/sentinel:latest -f coupe-sentinel/Dockerfile .
  release:example:blog:
    cmds:
      - docker build -t coupe/example-blog:latest -f example/blog/Dockerfile example/blog
