version: "3"

tasks:
  cli:dev:
    dir: "./cli"
    cmds:
      - deno run -A ./index.ts {{.CLI_ARGS}}

  cli:build:
    dir: "./cli"
    cmds:
      - deno compile -A --output coupe ./index.ts
      - mkdir -p build
      - mv coupe build/coupe

  install:
    cmds:
      - task: cli:build
      - sudo cp ./cli/build/coupe /usr/local/bin/coupe
      - mkdir -p $HOME/.coupe
      - rm -rf $HOME/.coupe/templates
      - cp -r ./templates $HOME/.coupe

  run:
    cmds:
      - node build/index.js {{.CLI_ARGS}}
