[package]
name = "coupe-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
thiserror = "2.0.12"
tokio = { version = "1", features = ["full"] }
coupe = { path = "../coupe" }
