[package]
name = "coupe-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
once_cell = "1.20.2"
opentelemetry = { version = "0.27.0", features = ["metrics"] }
opentelemetry-appender-tracing = "0.27.0"
opentelemetry-otlp = { version = "0.27.0", features = [
  "http-proto",
  "metrics",
  "logs",
] }
opentelemetry-semantic-conventions = { version = "0.27.0", features = [
  "semconv_experimental",
] }
opentelemetry_sdk = { version = "0.27.0", features = ["rt-tokio"] }
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.40"
tracing-opentelemetry = "0.28.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
